### PR TITLE
Neil - Announcement Form and fixes

### LINKED ISSUE #15: FEATURE: Frontend Form component for Announcements on Play Page
There is a form component for announcements suitable for crud operations (similar to team03 form components, but with a nice large text area for the announcement text.) Note that the commonsId is not part of the form; it will be set implicitly.

### PR DESCRIPTION
**Pull request by neil-roy**
## Overview

This pull request includes several changes to the frontend and backend components related to the announcement feature. The most important changes include modifications to the `AnnouncementForm` component, the creation of the `AdminCreateAnnouncementsPage` component, updates to the `AnnouncementsController`, and the addition of new tests.

These changes improve the functionality and reliability of the announcement creation feature in the application.

- Added form component implementation and functionality for Create Announcement 
- Created the Create Announcement Page (for admins, specific to the commons)
- Fixed backend code in AnnouncementsController.js and added additional testing
- Fixed POST operation (announcementID field is set automatically)
- Added default start date (to todays date and time)
- Fixed time difference for PST causing errors

## Screenshots (Optional)

Screenshot 2024-11-26 at 3 41 31 PM
Screenshot 2024-11-26 at 3 27 56 PM
Screenshot 2024-11-26 at 3 27 49 PM
Screenshot 2024-11-26 at 3 46 44 PM

## Future Possibilities (Optional)

Some possible points could be:
- On the Admin Announcements Page add:
- Delete Button
- Edit Button
- Get Button (shows table with edit next to each announcement)

## Validation (Optional)

1. go to dokku deployment: [https://happycows-dev-neil-roy.dokku-09.cs.ucsb.edu](https://happycows-dev-neil-roy.dokku-09.cs.ucsb.edu)
2. Sign in (admin account)
3. Click admin at the top, then list commons
4. On the right of the table, click announcements for any of the commons
5. click create announcment
6. fill out the form, test
7. Go to swagger UI and getbyID to test further

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #15

### CODE REVIEW

File: frontend/src/main/components/Announcement/AnnouncementForm.js [hunk 1]
```diff
@@ -21,9 +21,6 @@ function AnnouncementForm({ initialContents, submitAction, buttonLabel = "Create
     // For explanation, see: https://stackoverflow.com/questions/3143070/javascript-regex-iso-datetime
     // Note that even this complex regex may still need some tweaks
```
Comment (pconrad) [inline frontend/src/main/components/Announcement/AnnouncementForm.js]: If you remove the line of code, please remove the comments that go with it.

File: frontend/src/main/components/Announcement/AnnouncementForm.js [hunk 2]
```diff
@@ -21,9 +21,6 @@ function AnnouncementForm({ initialContents, submitAction, buttonLabel = "Create
...
 
-    // Stryker disable next-line Regex
-    const isodate_regex = /(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d\.\d+)|(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d)|(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d)/i;
-
     // Stryker disable next-line all
     //const yyyyq_regex = /((19)|(20))\d{2}[1-4]/i; // Accepts from 1900-2099 followed by 1-4.  Close enough.
```
Comment (pconrad) [inline frontend/src/main/components/Announcement/AnnouncementForm.js]: It looks like this is left over commented out code; as long as you are deleting things, let's delete this too.

File: frontend/src/main/components/Announcement/AnnouncementForm.js [hunk 3]
```diff
@@ -56,27 +53,28 @@ function AnnouncementForm({ initialContents, submitAction, buttonLabel = "Create
...
+                    isInvalid={Boolean(errors.startDate)}
                     {...register("endDate", {
-                        pattern: isodate_regex
+                        required: "endDate is required.",
                     })}
                 />
+                <Form.Control.Feedback type="invalid">
+                    {errors.endDate && 'End Date is required and must be provided in ISO format.'}
+                </Form.Control.Feedback>
             </Form.Group>
```
Comment (pconrad) [inline frontend/src/main/components/Announcement/AnnouncementForm.js]: Why are we making end date required?

It was a feature, not a bug that it was optional.  That allows you to put in an announcement that stays up indefinitely.

File: src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java [hunk 4]
```diff
@@ -3,6 +3,7 @@
 import com.fasterxml.jackson.databind.ObjectMapper;
 import io.swagger.v3.oas.annotations.tags.Tag;
 import lombok.extern.slf4j.Slf4j;
+import wiremock.org.checkerframework.checker.units.qual.s;
```
Comment (pconrad) [inline src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java]: Why?  I suspect this was a typo.  Can we remove this?

**Review by pconrad — COMMENTED** [review]
a couple of things I noticed...

File: frontend/src/main/components/Announcement/AnnouncementForm.js (hunk 3 above)
Comment (neil-roy) [reply frontend/src/main/components/Announcement/AnnouncementForm.js]: I thought that It would prevent mistakes as we don't have a delete announcement or edit announcement functionality yet on the frontend. 

I added the change - end date is no longer required (and updated the tests)

File: src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java [hunk 5]
```diff
@@ -67,10 +73,26 @@ public ResponseEntity<Object> createAnnouncement(
...
             startDate = new Date(); 
         }
+        if (endDate != null) {
+            Calendar calendar = Calendar.getInstance(); 
+            calendar.setTime(endDate);
+
+            calendar.set(Calendar.HOUR_OF_DAY, 8); 
+            endDate = calendar.getTime();
+        }
+
```
Comment (pconrad) [inline src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java:95]: There's a better way to do this (actually I can think of several better ways to do this.)

But we'll leave it to the S25 students to fix it.

**Review by pconrad — APPROVED** [review]
I would have preferred to see better handling of the time zone code, but this is good enough for now.

**Review by elijahelephant — APPROVED** [review]
Sorry for the delay,  LGTM
